### ISSUE TITLE
Option for image support instead of underline

### ISSUE THREAD

**Issue by whitmanc** [skv-headless/react-native-scrollable-tab-view#262]
Firstly, thanks for the great package! Second, we'd like to replace the underline with a triangle (i.e., a custom image). 

Two questions:

1. Is there any way to achieve this without modifying the package? (i.e., overriding [render()](https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/ScrollableTabBar.js#L145) somehow in our project)
2. Would it make sense to make this aspect of the tabs customizable ? If so, I would be willing to work on putting a PR up to propose

**Comment by skv-headless** [comment]
Like here https://github.com/skv-headless/react-native-scrollable-tab-view#injecting-a-custom-tab-bar you can do what ever you want. I'm thinking about other ways of customizing component. But before implementing this better to discuss in issue.

**Comment by whitmanc** [comment]
Appreciate that reference. I found what I need to do in an example as well: https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabBar.js#L49-L66

thanks again.

**Comment by cande1gut** [comment]
Hi, just in case someone wants to change the underline for a figure, it is possible by refactoring the style of the underline and you can do it by checking this post: [The Shapes of React Native](http://browniefed.com/blog/the-shapes-of-react-native/), where instead of using images you can create figures from the style. 

I was a little lost but found this and changed the style of tabUnderlineStyle in DefaultTabBar.js and is working cool.

**Comment by skv-headless** [comment]
@cande1gut awesome article. Now I know how to implement #253. Thanks.
