### ISSUE TITLE
Using ListView with TouchableOpacity on tab view

### ISSUE THREAD

**Issue by Ashok93** [skv-headless/react-native-scrollable-tab-view#338]
I am trying to use TouchableOpacity with tab elements. The elements responds but I am not able to scroll the list. Please help me with this. Thanks.
```
return (
      <ScrollableTabView tabBarUnderlineColor='red' onChangeTab = {this.setIndianState.bind(this)}>
      <View>
        <ListView tabLabel="Movies"
         />
        <ListView tabLabel="About"
         />
        </View>
       </ScrollableTabView>
```
I am using the TouchableOpacity on the list of movies returned by a function. I want to alert when pressed and not scrolled.

**Comment by skv-headless** [comment]
In your code snippet I don't see TouchableOpacity. Also better to post this question to stackoverflow.

**Comment by MasoudShah** [comment]
I have this kind of problem too, they are similar. I have multiple tabs inside ScrollableTabView and some of them are FlatList. The items of FlatList are wrapped inside a TouchableWithoutFeedback with onPress property. Scrolling vertical is OK and the FlatLists have no issue but Scrolling horizontal has an issue. When you scroll horizontally on an Item of FlatList, scrolling wont happen and the onPress of TouchableWithoutFeedback triggers; but if your point of touch is not on the items and between them, it scrolls normally. The problem is scrolling horizontal doesn't steals the responder lock of TouchableWithoutFeedback. How can I overcome this problem?
